# Generated by Django 3.0.7 on 2022-04-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Unknown', max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(default='Unknown', max_length=500)),
                ('content', models.TextField(default='Unknown')),
                ('director', models.CharField(default='Unknown', max_length=500)),
                ('cast', models.CharField(default='Unknown', max_length=500)),
                ('country', models.CharField(default='Unknown', max_length=500)),
                ('genres', models.TextField(default='Unknown', max_length=500)),
                ('duration', models.CharField(default='Unknown', max_length=500)),
                ('release_date', models.IntegerField()),
                ('post_date', models.CharField(default='02/04/2022', max_length=500)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(default='default.mp4', upload_to='video/%y')),
                ('name', models.CharField(max_length=500)),
                ('type', models.CharField(default='Unknown', max_length=500)),
                ('content', models.TextField(default='Unknown')),
                ('rating', models.CharField(default='Unknown', max_length=20)),
                ('director', models.CharField(default='Unknown', max_length=500)),
                ('cast', models.CharField(default='Unknown', max_length=500)),
                ('country', models.CharField(default='Unknown', max_length=500)),
                ('genres', models.TextField(default='Unknown', max_length=500)),
                ('duration', models.CharField(default='Unknown', max_length=500)),
                ('release_date', models.IntegerField()),
                ('post_date', models.CharField(default='02/04/2022', max_length=500)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WatchLater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='Unknown', max_length=500)),
                ('name', models.CharField(max_length=500)),
            ],
        ),
    ]
