# Generated by Django 3.0.7 on 2022-04-02 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='post_date',
            field=models.CharField(default='03/04/2022', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.CharField(default='03/04/2022', max_length=500),
        ),
    ]
