# Generated by Django 3.1.4 on 2021-03-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_area'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BedRequest',
        ),
        migrations.RemoveField(
            model_name='post',
            name='address',
        ),
        migrations.RemoveField(
            model_name='post',
            name='area',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='city',
        ),
        migrations.RemoveField(
            model_name='post',
            name='covid_cap',
        ),
        migrations.RemoveField(
            model_name='post',
            name='norm_cap',
        ),
        migrations.AddField(
            model_name='post',
            name='cast',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='director',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='duration',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='genres',
            field=models.TextField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='release_date',
            field=models.CharField(default='24/03/2021', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Unknown'),
        ),
    ]
