# Generated by Django 3.1.4 on 2021-03-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20210325_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
