# Generated by Django 3.1.4 on 2021-03-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='release_date',
            field=models.CharField(default='27/03/2021', max_length=100),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='release_date',
            field=models.CharField(default='27/03/2021', max_length=100),
        ),
    ]
