# Generated by Django 3.1.4 on 2021-03-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20210327_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlater',
            name='user',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
