# Generated by Django 3.1.4 on 2021-05-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20210401_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlater',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='watchlater',
            name='content',
        ),
        migrations.RemoveField(
            model_name='watchlater',
            name='country',
        ),
        migrations.RemoveField(
            model_name='watchlater',
            name='director',
        ),
        migrations.RemoveField(
            model_name='watchlater',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='watchlater',
            name='genres',
        ),
        migrations.RemoveField(
            model_name='watchlater',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='watchlater',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='watchlater',
            name='type',
        ),
        migrations.AddField(
            model_name='liked',
            name='post_date',
            field=models.CharField(default='28/05/2021', max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.CharField(default='28/05/2021', max_length=500),
        ),
        migrations.AlterField(
            model_name='liked',
            name='cast',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='liked',
            name='country',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='liked',
            name='director',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='liked',
            name='duration',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='liked',
            name='genres',
            field=models.TextField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='liked',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='liked',
            name='release_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='liked',
            name='type',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='liked',
            name='user',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='cast',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='director',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='duration',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='genres',
            field=models.TextField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='release_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default='Unknown', max_length=500),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='watchlater',
            name='user',
            field=models.CharField(default='Unknown', max_length=500),
        ),
    ]
